### ISSUE TITLE
nav() fungerar inte.

### ISSUE THREAD

**Issue by MatAlt** [jeer00/ava-pricefinder#1]
Tack för en bra funktion! 

Jag får inte nav() att fungera, resulterar bara i "#ERROR" samt utförligare "Fel
Exception: Request failed for https://www.avanza.se returned code 404. Truncated server response: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </head> <body><h2>HTTP ERROR 4... (use muteHttpExceptions option to examine full response) (rad 37)."

lastPrice() fungerar dock utmärkt. 
Är ny på det här, så kan mycket väl vara jag som gjort ngt fel i implementeringen. 

/M

**Comment by jeer00** [comment]
Det här projektet är tyvärr något som inte blivit uppdaterat. Avanza har gjort om sidan för fonder och därför fungerar inte scriptet. Ska se om jag hinner fixa scriptet inom kort!

**Comment by jeer00** [comment]
Sjukt sent svar, men behövde nav själv så uppdaterade scriptet så nu fungerar även fonder :)
